//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="KVList", Namespace="http://www.genesyslab.com/interaction", ItemName="kvitem")]
    [System.SerializableAttribute()]
    public class KVList : System.Collections.Generic.List<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVPair> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KVPair", Namespace="http://www.genesyslab.com/interaction")]
    [System.SerializableAttribute()]
    public partial class KVPair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string keyField;
        
        private Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVPairValue valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVPairValue value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KVPairValue", Namespace="http://www.genesyslab.com/interaction")]
    [System.SerializableAttribute()]
    public partial class KVPairValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList ValueListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValueInt {
            get {
                return this.ValueIntField;
            }
            set {
                if ((this.ValueIntField.Equals(value) != true)) {
                    this.ValueIntField = value;
                    this.RaisePropertyChanged("ValueInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ValueString {
            get {
                return this.ValueStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueStringField, value) != true)) {
                    this.ValueStringField = value;
                    this.RaisePropertyChanged("ValueString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList ValueList {
            get {
                return this.ValueListField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueListField, value) != true)) {
                    this.ValueListField = value;
                    this.RaisePropertyChanged("ValueList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://www.genesyslab.com/interaction")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        private string ErrorDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.genesyslab.com/interaction", ConfigurationName="ServiceReference5.iWebServiceCapturePoint")]
    public interface iWebServiceCapturePoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.FaultMessage), Action="", Name="FaultMessage")]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitOutputMessage Submit(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitInputMessage request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitOutputMessage> SubmitAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitInputMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.FaultMessage), Action="", Name="FaultMessage")]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldOutputMessage Hold(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldInputMessage request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldOutputMessage> HoldAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldInputMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.FaultMessage), Action="", Name="FaultMessage")]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopOutputMessage Stop(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopInputMessage request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopOutputMessage> StopAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopInputMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.FaultMessage), Action="", Name="FaultMessage")]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateOutputMessage Update(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateInputMessage request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateOutputMessage> UpdateAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateInputMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.FaultMessage), Action="", Name="FaultMessage")]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeOutputMessage Resume(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeInputMessage request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeOutputMessage> ResumeAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeInputMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingOutputMessage Ping(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingInputMessage request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingOutputMessage> PingAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingInputMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.FaultMessage), Action="", Name="FaultMessage")]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoOutputMessage GetInfo(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoInputMessage request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoOutputMessage> GetInfoAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoInputMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Submit", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointSubmitInputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public string InteractionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=1)]
        public string ExternalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=2)]
        public string MediaType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=3)]
        public string InteractionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=4)]
        public string InteractionSubtype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=5)]
        public System.Nullable<int> TenantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=6)]
        public string Queue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=7)]
        public string Workbin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=8)]
        public string WorkbinAgentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=9)]
        public string WorkbinAgentGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=10)]
        public string WorkbinPlaceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=11)]
        public string WorkbinPlaceGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=12)]
        public string ParentInteractionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=13)]
        public bool IsOnline;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=14)]
        public string ReceivedAt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=15)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList InQueues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=16)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList OutQueues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=17)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList UserData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=18)]
        public System.Nullable<bool> Hold;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=19)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointSubmitInputMessage() {
        }
        
        public iWebServiceCapturePointSubmitInputMessage(
                    string InteractionId, 
                    string ExternalId, 
                    string MediaType, 
                    string InteractionType, 
                    string InteractionSubtype, 
                    System.Nullable<int> TenantId, 
                    string Queue, 
                    string Workbin, 
                    string WorkbinAgentId, 
                    string WorkbinAgentGroupId, 
                    string WorkbinPlaceId, 
                    string WorkbinPlaceGroupId, 
                    string ParentInteractionId, 
                    bool IsOnline, 
                    string ReceivedAt, 
                    Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList InQueues, 
                    Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList OutQueues, 
                    Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList UserData, 
                    System.Nullable<bool> Hold, 
                    Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.InteractionId = InteractionId;
            this.ExternalId = ExternalId;
            this.MediaType = MediaType;
            this.InteractionType = InteractionType;
            this.InteractionSubtype = InteractionSubtype;
            this.TenantId = TenantId;
            this.Queue = Queue;
            this.Workbin = Workbin;
            this.WorkbinAgentId = WorkbinAgentId;
            this.WorkbinAgentGroupId = WorkbinAgentGroupId;
            this.WorkbinPlaceId = WorkbinPlaceId;
            this.WorkbinPlaceGroupId = WorkbinPlaceGroupId;
            this.ParentInteractionId = ParentInteractionId;
            this.IsOnline = IsOnline;
            this.ReceivedAt = ReceivedAt;
            this.InQueues = InQueues;
            this.OutQueues = OutQueues;
            this.UserData = UserData;
            this.Hold = Hold;
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestResponse", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointSubmitOutputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointSubmitOutputMessage() {
        }
        
        public iWebServiceCapturePointSubmitOutputMessage(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Hold", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointHoldInputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public string InteractionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=1)]
        public string ExternalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=2)]
        public string ReasonSystemName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=3)]
        public string ReasonDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=4)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointHoldInputMessage() {
        }
        
        public iWebServiceCapturePointHoldInputMessage(string InteractionId, string ExternalId, string ReasonSystemName, string ReasonDescription, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.InteractionId = InteractionId;
            this.ExternalId = ExternalId;
            this.ReasonSystemName = ReasonSystemName;
            this.ReasonDescription = ReasonDescription;
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestResponse", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointHoldOutputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointHoldOutputMessage() {
        }
        
        public iWebServiceCapturePointHoldOutputMessage(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Stop", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointStopInputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public string InteractionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=1)]
        public string ExternalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=2)]
        public string ReasonSystemName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=3)]
        public string ReasonDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=4)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointStopInputMessage() {
        }
        
        public iWebServiceCapturePointStopInputMessage(string InteractionId, string ExternalId, string ReasonSystemName, string ReasonDescription, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.InteractionId = InteractionId;
            this.ExternalId = ExternalId;
            this.ReasonSystemName = ReasonSystemName;
            this.ReasonDescription = ReasonDescription;
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestResponse", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointStopOutputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointStopOutputMessage() {
        }
        
        public iWebServiceCapturePointStopOutputMessage(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointUpdateInputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public string InteractionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=1)]
        public string ExternalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=2)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Changed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=3)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Deleted;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=4)]
        public string Queue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=5)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointUpdateInputMessage() {
        }
        
        public iWebServiceCapturePointUpdateInputMessage(string InteractionId, string ExternalId, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Changed, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Deleted, string Queue, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.InteractionId = InteractionId;
            this.ExternalId = ExternalId;
            this.Changed = Changed;
            this.Deleted = Deleted;
            this.Queue = Queue;
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestResponse", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointUpdateOutputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointUpdateOutputMessage() {
        }
        
        public iWebServiceCapturePointUpdateOutputMessage(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Resume", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointResumeInputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public string InteractionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=1)]
        public string ExternalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=2)]
        public string ReasonSystemName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=3)]
        public string ReasonDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=4)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointResumeInputMessage() {
        }
        
        public iWebServiceCapturePointResumeInputMessage(string InteractionId, string ExternalId, string ReasonSystemName, string ReasonDescription, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.InteractionId = InteractionId;
            this.ExternalId = ExternalId;
            this.ReasonSystemName = ReasonSystemName;
            this.ReasonDescription = ReasonDescription;
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestResponse", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointResumeOutputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointResumeOutputMessage() {
        }
        
        public iWebServiceCapturePointResumeOutputMessage(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointPingInputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointPingInputMessage() {
        }
        
        public iWebServiceCapturePointPingInputMessage(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointPingOutputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public string EventTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=1)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList UserData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=2)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList PingInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=3)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointPingOutputMessage() {
        }
        
        public iWebServiceCapturePointPingOutputMessage(string EventTime, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList UserData, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList PingInfo, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.EventTime = EventTime;
            this.UserData = UserData;
            this.PingInfo = PingInfo;
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInfo", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointGetInfoInputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public string InteractionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=1)]
        public string ExternalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=2)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        public iWebServiceCapturePointGetInfoInputMessage() {
        }
        
        public iWebServiceCapturePointGetInfoInputMessage(string InteractionId, string ExternalId, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            this.InteractionId = InteractionId;
            this.ExternalId = ExternalId;
            this.Extension = Extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInfoRequestResponse", WrapperNamespace="http://www.genesyslab.com/interaction", IsWrapped=true)]
    public partial class iWebServiceCapturePointGetInfoOutputMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=0)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.genesyslab.com/interaction", Order=1)]
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList InteractionProperties;
        
        public iWebServiceCapturePointGetInfoOutputMessage() {
        }
        
        public iWebServiceCapturePointGetInfoOutputMessage(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList InteractionProperties) {
            this.Extension = Extension;
            this.InteractionProperties = InteractionProperties;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iWebServiceCapturePointChannel : Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iWebServiceCapturePointClient : System.ServiceModel.ClientBase<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint>, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint {
        
        public iWebServiceCapturePointClient() {
        }
        
        public iWebServiceCapturePointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iWebServiceCapturePointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iWebServiceCapturePointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iWebServiceCapturePointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitOutputMessage Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint.Submit(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitInputMessage request) {
            return base.Channel.Submit(request);
        }
        
        public void Submit(
                    string InteractionId, 
                    string ExternalId, 
                    string MediaType, 
                    string InteractionType, 
                    string InteractionSubtype, 
                    System.Nullable<int> TenantId, 
                    string Queue, 
                    string Workbin, 
                    string WorkbinAgentId, 
                    string WorkbinAgentGroupId, 
                    string WorkbinPlaceId, 
                    string WorkbinPlaceGroupId, 
                    string ParentInteractionId, 
                    bool IsOnline, 
                    string ReceivedAt, 
                    Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList InQueues, 
                    Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList OutQueues, 
                    Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList UserData, 
                    System.Nullable<bool> Hold, 
                    ref Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitInputMessage inValue = new Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitInputMessage();
            inValue.InteractionId = InteractionId;
            inValue.ExternalId = ExternalId;
            inValue.MediaType = MediaType;
            inValue.InteractionType = InteractionType;
            inValue.InteractionSubtype = InteractionSubtype;
            inValue.TenantId = TenantId;
            inValue.Queue = Queue;
            inValue.Workbin = Workbin;
            inValue.WorkbinAgentId = WorkbinAgentId;
            inValue.WorkbinAgentGroupId = WorkbinAgentGroupId;
            inValue.WorkbinPlaceId = WorkbinPlaceId;
            inValue.WorkbinPlaceGroupId = WorkbinPlaceGroupId;
            inValue.ParentInteractionId = ParentInteractionId;
            inValue.IsOnline = IsOnline;
            inValue.ReceivedAt = ReceivedAt;
            inValue.InQueues = InQueues;
            inValue.OutQueues = OutQueues;
            inValue.UserData = UserData;
            inValue.Hold = Hold;
            inValue.Extension = Extension;
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitOutputMessage retVal = ((Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint)(this)).Submit(inValue);
            Extension = retVal.Extension;
        }
        
        public System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitOutputMessage> SubmitAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointSubmitInputMessage request) {
            return base.Channel.SubmitAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldOutputMessage Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint.Hold(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldInputMessage request) {
            return base.Channel.Hold(request);
        }
        
        public void Hold(string InteractionId, string ExternalId, string ReasonSystemName, string ReasonDescription, ref Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldInputMessage inValue = new Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldInputMessage();
            inValue.InteractionId = InteractionId;
            inValue.ExternalId = ExternalId;
            inValue.ReasonSystemName = ReasonSystemName;
            inValue.ReasonDescription = ReasonDescription;
            inValue.Extension = Extension;
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldOutputMessage retVal = ((Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint)(this)).Hold(inValue);
            Extension = retVal.Extension;
        }
        
        public System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldOutputMessage> HoldAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointHoldInputMessage request) {
            return base.Channel.HoldAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopOutputMessage Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint.Stop(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopInputMessage request) {
            return base.Channel.Stop(request);
        }
        
        public void Stop(string InteractionId, string ExternalId, string ReasonSystemName, string ReasonDescription, ref Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopInputMessage inValue = new Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopInputMessage();
            inValue.InteractionId = InteractionId;
            inValue.ExternalId = ExternalId;
            inValue.ReasonSystemName = ReasonSystemName;
            inValue.ReasonDescription = ReasonDescription;
            inValue.Extension = Extension;
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopOutputMessage retVal = ((Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint)(this)).Stop(inValue);
            Extension = retVal.Extension;
        }
        
        public System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopOutputMessage> StopAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointStopInputMessage request) {
            return base.Channel.StopAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateOutputMessage Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint.Update(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateInputMessage request) {
            return base.Channel.Update(request);
        }
        
        public void Update(string InteractionId, string ExternalId, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Changed, Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Deleted, string Queue, ref Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateInputMessage inValue = new Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateInputMessage();
            inValue.InteractionId = InteractionId;
            inValue.ExternalId = ExternalId;
            inValue.Changed = Changed;
            inValue.Deleted = Deleted;
            inValue.Queue = Queue;
            inValue.Extension = Extension;
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateOutputMessage retVal = ((Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint)(this)).Update(inValue);
            Extension = retVal.Extension;
        }
        
        public System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateOutputMessage> UpdateAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointUpdateInputMessage request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeOutputMessage Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint.Resume(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeInputMessage request) {
            return base.Channel.Resume(request);
        }
        
        public void Resume(string InteractionId, string ExternalId, string ReasonSystemName, string ReasonDescription, ref Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeInputMessage inValue = new Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeInputMessage();
            inValue.InteractionId = InteractionId;
            inValue.ExternalId = ExternalId;
            inValue.ReasonSystemName = ReasonSystemName;
            inValue.ReasonDescription = ReasonDescription;
            inValue.Extension = Extension;
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeOutputMessage retVal = ((Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint)(this)).Resume(inValue);
            Extension = retVal.Extension;
        }
        
        public System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeOutputMessage> ResumeAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointResumeInputMessage request) {
            return base.Channel.ResumeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingOutputMessage Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint.Ping(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingInputMessage request) {
            return base.Channel.Ping(request);
        }
        
        public string Ping(ref Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension, out Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList UserData, out Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList PingInfo) {
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingInputMessage inValue = new Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingInputMessage();
            inValue.Extension = Extension;
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingOutputMessage retVal = ((Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint)(this)).Ping(inValue);
            UserData = retVal.UserData;
            PingInfo = retVal.PingInfo;
            Extension = retVal.Extension;
            return retVal.EventTime;
        }
        
        public System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingOutputMessage> PingAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointPingInputMessage request) {
            return base.Channel.PingAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoOutputMessage Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint.GetInfo(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoInputMessage request) {
            return base.Channel.GetInfo(request);
        }
        
        public Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList GetInfo(string InteractionId, string ExternalId, ref Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.KVList Extension) {
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoInputMessage inValue = new Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoInputMessage();
            inValue.InteractionId = InteractionId;
            inValue.ExternalId = ExternalId;
            inValue.Extension = Extension;
            Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoOutputMessage retVal = ((Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePoint)(this)).GetInfo(inValue);
            Extension = retVal.Extension;
            return retVal.InteractionProperties;
        }
        
        public System.Threading.Tasks.Task<Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoOutputMessage> GetInfoAsync(Genesyslab.Desktop.Modules.CiscoVoice.ServiceReference5.iWebServiceCapturePointGetInfoInputMessage request) {
            return base.Channel.GetInfoAsync(request);
        }
    }
}
